# Generated by Django 5.2.7 on 2025-10-31 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Femea")], max_length=1
                    ),
                ),
                ("cor", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("disponivel", models.BooleanField(default=True)),
                (
                    "raca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gatos",
                        to="adocato.raca",
                    ),
                ),
            ],
        ),
    ]
