# Generated by Django 5.2.7 on 2025-10-31 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0002_gato"),
    ]

    operations = [
        migrations.AddField(
            model_name="gato",
            name="data_nascimento",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
