# Generated by Django 5.2.7 on 2025-11-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adocato", "0003_gato_data_nascimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="gato",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_gatos/"),
        ),
    ]
